### ISSUE TITLE
Typeerror when loggin in

### ISSUE THREAD

**Issue by drdoof2019** [softcoder24/instagram-share-post#3]
Hi,
`TypeError: cannot unpack non-iterable NoneType object`
This is error in detail:
`login failed  {"user": false, "authenticated": false, "status": "ok"}
Traceback (most recent call last):
  File "c:/Users/User/Desktop/instagram-share-post-master/instagram.py", line 116, in <module>
    share_photo(photo="toronto.jpg", caption="This is awesome")
  File "c:/Users/User/Desktop/instagram-share-post-master/instagram.py", line 53, in share_photo
    csrf_token, session_id = login_instagram(insta_user, insta_password)
TypeError: cannot unpack non-iterable NoneType object`

Also can you please take a video or make an explanation how to code this program? I want to add extra functions like follow, like etc. Waiting for your response.

Edit: I forget that I changed my pass so I corrected it and code worked awasome! But I still need help about :

> Also can you please take a video or make an explanation how to code this program? I want to add extra functions like follow, like etc. Waiting for your response.

**Comment by softcoder24** [comment]
Hi 
There is a problem with the login function. the Instagram server knows when we log in via the requests and it asks us to verify our account then you can be logged in successfully.
I am going to work on it if I solve I will update the code. Also, I am going to make a package of this script soon!

**Comment by drdoof2019** [comment]
thank you @softcoder24 , If you can make a short video about how to find those headers etc. Humanity would be very happy:)
I know requests module and finding via chrome inspect tool in network page but I cannot find what you find. For example I could not find login adress\ajax page, I dont know how to find an adress to upload ig server a photo. You are awasome my friend.
